### PR TITLE
chore: updated to version 1.5

### LINKED ISSUE #9: Update to openshift 1.5
Openshift 1.5 is now avaliable.

### PR DESCRIPTION
**Pull request by dwmkerr**
Also updated docs with more instructions on how to set the openshift version. Closes #9.

### CODE REVIEW

**Comment by mpaltun** [comment]
I confirm that this is working without problems.

**Comment by dwmkerr** [comment]
Brilliant, thanks so much for checking!

**Comment by mpaltun** [comment]
Thanks for the project :) It was pretty easy to setup.

**Comment by dwmkerr** [comment]
No worries, glad it was useful!

**Pull request merged**
