### PR TITLE
add k8s aws and dynamic pv support (fixes #3)

### LINKED ISSUE #3: Support Persistent Volumes
Two options:

a. AWS EFS. Easy, but only available in a few regions
b. AWS EBS. Harder, single AZ only, but global.

Probably go for the first one to start with

### PR DESCRIPTION
**Pull request by bkconrad**
Configure the kubernetes AWS cloud provider support through openshift. This by extension enables persistent volume support with dynamic provisioning through k8s (closing #3 ). Confirmed by testing with the persistent rails sample app.

To support this I had to use the internal AWS hostnames in the inventory, which in turn required outputting the inventory. See:
https://github.com/openshift/openshift-ansible/issues/5692

IAM Policies are taken from the AWS reference architecture. They are configured using access key pairs so that containers don't have access to the host's permissions via instance profile.

I plan to further generalize this module to support configurable host counts and sizes, which will build on the inventory generation in this PR.

### CODE REVIEW

**Comment by dwmkerr** [comment]
@bkconrad this is really, really nice! It cleans up a few issues which have been nagging at me for a while, and the removal of the whole `sed` step to generate the inventory is a great improvement. 

I'm going to create the cluster and run some tests now, I'll also update the docs describing a little more about PVs and how to use them with this set up. Will probably be the end of the weekend before I can merge as I'm pretty swamped, but I'm super happy with these changes!

**Comment by stevenhaddox** [comment]
We ran this PR last Friday and it seems to have fixed our persistent storage issues with Jenkins in OpenShift (which was our first failing thing). Looks promising as a new user to this repo :)

**Comment by dwmkerr** [comment]
Brilliant, thanks for sharing @stevenhaddox! Hoping to get this in the mainline very soon, just a bit swamped at work this week! Am also adding some extra testing facilities and docs explaining how to use the PVs :smil

**Comment by dwmkerr** [comment]
*Work In Progress*

I'll update these notes while I work on integration.

*Inventory*

I *love* the removal of the grotty `sed` command with the much cleaner terraform templating for `inventory.cfg`. However, I've removed the inventory section from the terraform variables, as I think for end users it is easier to quickly open the `inventory.template.cfg` to edit the node labels and see what their inventory will be, rather than having to jump to the terraform code for this.

*Hostnames*

I used the private addresses for the hosts in the inventory (essentially copying what was in the terraform template back into the inventory) but noticed that we end up with the AWS hostnames:

image

Ideally I'd like to keep the hosts as `nodeX.openshift.local` as when debugging or looking at logs etc, it is much clearer to have the internal DNS name rather than the AWS generated hostname. However, I'm still testing this now to make sure it works with PVs (don't want to break the feature). I'll also raise an issue to set the actual `host` value on each node, so that the hostname is properly set on each instance (not just on the internal DNS).

**Pull request merged**
