### PR TITLE
Update makefile

### PR DESCRIPTION
**Pull request by jayunit100**
disable strict host checking for more automation-friendly behaviopur

### CODE REVIEW

**Comment by jayunit100** [comment]
@dwmkerr need this for full automation right ?

**Comment by dwmkerr** [comment]
I think this is not needed because the `makefile` does this first:

```bash
        # Add our identity for ssh, add the host key to avoid having to accept the
	# the host key manually. Also add the identity of each node to the bastion.
	ssh-add ~/.ssh/id_rsa
	ssh-keyscan -t rsa -H $$(terraform output bastion-public_dns) >> ~/.ssh/known_hosts
	ssh -A ec2-user@$$(terraform output bastion-public_dns) "ssh-keyscan -t rsa -H master.openshift.local >> ~/.ssh/known_hosts"
	ssh -A ec2-user@$$(terraform output bastion-public_dns) "ssh-keyscan -t rsa -H node1.openshift.local >> ~/.ssh/known_hosts"
	ssh -A ec2-user@$$(terraform output bastion-public_dns) "ssh-keyscan -t rsa -H node2.openshift.local >> ~/.ssh/known_hosts"
```

This adds the host to the known hosts, both on the local machine, but also the bastion (meaning that first time you connect to the bastion, you don't need to accept the host when jumping to another host, which comes in a little later on in the splunk work I'm doing)

**Comment by jayunit100** [comment]
Hmmmm; ok...

**Comment by dwmkerr** [comment]
Looks like this PR is not needed, please re-open if you see any issues!

**Pull request closed without merging**
